name: Build latest master and deploy

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.11.0
        with:
          java-version: 21
          java-distribution: liberica
          checkout-persist-credentials: true
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build with Maven
        run: mvn spring-boot:build-image -Pnative

      - name: Push Images to Docker Registry
        run: docker push -a bjoggis/sparebank1-data-fetcher
  manifest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: pull-arm64
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          retry_wait_seconds: 60
          max_attempts: 8
          command: docker pull bjoggis/sparebank1-data-fetcher:${{ github.ref_name }}-aarch_64
      - name: create-manifest
        run: |
          docker manifest create bjoggis/sparebank1-data-fetcher:${{ github.ref_name }} --amend bjoggis/sparebank1-data-fetcher:${{ github.ref_name }}-x86_64 --amend bjoggis/sparebank1-data-fetcher:${{ github.ref_name }}-aarch_64
          docker manifest push bjoggis/sparebank1-data-fetcher:${{ github.ref_name }}
          docker manifest create bjoggis/sparebank1-data-fetcher:latest --amend bjoggis/sparebank1-data-fetcher:${{ github.ref_name }}-x86_64 --amend bjoggis/sparebank1-data-fetcher:${{ github.ref_name }}-aarch_64
          docker manifest push bjoggis/sparebank1-data-fetcher:latest
